version: '3.8'

services:
  petcode-webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_HOST_NAME: db
      DB_USERNAME: petcode
      DB_PASSWORD: S3cret
      DB_NAME: petcode
      JWT_SECRET_KEY: HideYourSecretKeyForJWTAuthentication
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:13-alpine
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U petcode" ]
      interval: 5s
      timeout: 30s
      retries: 8
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: petcode
      POSTGRES_PASSWORD: S3cret
      POSTGRES_DB: petcode
    ports:
      - 5432:5432

volumes:
  postgres_data:
